name: Increment Visitor Counter

on:
  workflow_dispatch: # handmatig triggeren, later evt. automatisch

jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read visitor_count.txt
        id: count
        run: |
          count=$(cat visitor_count.txt)
          echo "count=$count" >> $GITHUB_OUTPUT
      - name: Increment counter
        run: |
          new_count=$(( ${{ steps.count.outputs.count }} + 1 ))
          echo $new_count > visitor_count.txt
      - name: Commit updated counter
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add visitor_count.txt
          git commit -m "Increment visitor counter"
          git push
